# UI for the agent using ChainLit framework to make a chat window.
import chainlit as cl
import os
from datetime import datetime 

"""
Set up the directory to save the output file generated by the agent.
"""
OUTPUT_DIR=os.path.join(os.getcwd(),"outputs")
os.makedirs(OUTPUT_DIR,exist_ok=True)

"""
Below contains the initial message the chat-bot sends the users way. 
It includes greetings, introduction of the bot and the details which the bot needs.
"""
@cl.on_chat_start
async def start():
    await cl.Message(
        content="Hello dear aspirant, I am your college advisor, here to help you.\n\n"
                "Tell me the details of the university you are targeting:\n"
                "* **University Name**\n"
                "* **Program Name**\n"
                "* **Level of study** (Bachelors, Masters, PhD)\n"
                "* **Background** (GPAm Country, College Tier etc.)\n"
                "When you provide me this information I will provide you with a document that comprises of strategy and information on the course you are aiming for!"
    ).send()

"""
Determines the steps after user responds with information. 
"""
@cl.on_message
async def main(message:cl.Message):
    # STEP 1: Extract the name of uni and the program name to use it for output file name.
    async with cl.Step(name="Identifying Target", type="tool") as step:
        # A LLM call that extracts the name of uni and the program and stores it in:
        uni_name="XYZ"
        program_name="CSE"

        clean_name=f"{uni_name}-{program_name}".replace(" ","-")
        step.output=f"Targeting: {uni_name} ({program_name})"

    # STEP 2: Document generation
    async with cl.Step(name="Strategist Agent",type="run")as agent_step:
        # Define the filename for this request
        filename=f"{clean_name}.docx"
        file_path=os.path.join(OUTPUT_DIR,filename)

        # Agentic logic/API calls
        # Agent should save the output to the specific file_path
        await cl.sleep(4)

        agent_step.output=f"Strategy for {uni_name} completed."
    
    # STEP 3: Delivery of the file to the user. 
    if os.path.exists(file_path):
        await cl.Message(
            content=f"I have generated your custom strategy for **{uni_name}**.",
            elements=[cl.File(name=filename,path=file_path,display="inline")]
        ).send()

